/*
Copyright (c) 2014-2015 F-Secure
See LICENSE for details
*/
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSecure.Lokki.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSecure.Lokki.Resources.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened, please try again..
        /// </summary>
        public static string ApiError {
            get {
                return ResourceManager.GetString("ApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security reasons we have temporarily put your account on hold. Maybe you recently signed up to Lokki from another device with the same email address and Lokki does not allow that.
        ///Please sign up again..
        /// </summary>
        public static string ApiError401 {
            get {
                return ResourceManager.GetString("ApiError401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-Secure Lokki.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like F-Secure Lokki?.
        /// </summary>
        public static string AppRaterDoYouLikeQuestion {
            get {
                return ResourceManager.GetString("AppRaterDoYouLikeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us feedback.
        /// </summary>
        public static string AppRaterDoYouLikeTitle {
            get {
                return ResourceManager.GetString("AppRaterDoYouLikeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My feedback for Lokki {0} (WP).
        /// </summary>
        public static string AppRaterFeedBackEmailSubject {
            get {
                return ResourceManager.GetString("AppRaterFeedBackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string AppRaterNo {
            get {
                return ResourceManager.GetString("AppRaterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Thanks.
        /// </summary>
        public static string AppRaterNoThanks {
            get {
                return ResourceManager.GetString("AppRaterNoThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me later.
        /// </summary>
        public static string AppRaterRemindLater {
            get {
                return ResourceManager.GetString("AppRaterRemindLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enjoy using F-Secure Lokki, please take a moment to rate it. Thanks for your support!.
        /// </summary>
        public static string AppRaterReviewQuestion {
            get {
                return ResourceManager.GetString("AppRaterReviewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Lokki.
        /// </summary>
        public static string AppRaterReviewQuestionTitle {
            get {
                return ResourceManager.GetString("AppRaterReviewQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Lokki team,
        ///I have some feedback for you:.
        /// </summary>
        public static string AppRaterSendFeedbackBodyWhenUserDoesNotLike {
            get {
                return ResourceManager.GetString("AppRaterSendFeedbackBodyWhenUserDoesNotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to send us feedback?.
        /// </summary>
        public static string AppRaterSendFeedbackQuestion {
            get {
                return ResourceManager.GetString("AppRaterSendFeedbackQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AppRaterYes {
            get {
                return ResourceManager.GetString("AppRaterYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ButtonDone {
            get {
                return ResourceManager.GetString("ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string ButtonLater {
            get {
                return ResourceManager.GetString("ButtonLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can see me.
        /// </summary>
        public static string CanSeeMe {
            get {
                return ResourceManager.GetString("CanSeeMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2013-2014 F-Secure Corporation. All rights reserved..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seems to have crashed. Would you like to help improve it by sending an anonymous crash report?
        ///
        ///The following e-mail contains diagnostic data about the app..
        /// </summary>
        public static string CrashDialogMessage {
            get {
                return ResourceManager.GetString("CrashDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash report.
        /// </summary>
        public static string CrashDialogTitle {
            get {
                return ResourceManager.GetString("CrashDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services are not enabled for Lokki. Please enable Location services for Lokki in system settings..
        /// </summary>
        public static string ErrorNoLocationService {
            get {
                return ResourceManager.GetString("ErrorNoLocationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://community.f-secure.com/t5/Security-for-PC/tkb-p/Protection%40tkb?sort_by=-topicPublishDate&amp;page=1&amp;restrictionStates=no_filter&amp;labels=lokki.
        /// </summary>
        public static string HelpLink {
            get {
                return ResourceManager.GetString("HelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        public static string IAgree {
            get {
                return ResourceManager.GetString("IAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible.
        /// </summary>
        public static string Invisible {
            get {
                return ResourceManager.GetString("Invisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inviting.
        /// </summary>
        public static string Inviting {
            get {
                return ResourceManager.GetString("Inviting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send invitation to {0}?.
        /// </summary>
        public static string InvitingConfirmMessage {
            get {
                return ResourceManager.GetString("InvitingConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to match the email with a contact to display photo and enable messaging features. This can happen with linked accounts.
        ///Would you like to add the email address to your contact?.
        /// </summary>
        public static string InvitingEmailNotFound {
            get {
                return ResourceManager.GetString("InvitingEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string MapModeAerial {
            get {
                return ResourceManager.GetString("MapModeAerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string MapModeHybrid {
            get {
                return ResourceManager.GetString("MapModeHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string MapModeRoad {
            get {
                return ResourceManager.GetString("MapModeRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        public static string MapModeTerrain {
            get {
                return ResourceManager.GetString("MapModeTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MenuButtonAdd {
            get {
                return ResourceManager.GetString("MenuButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible.
        /// </summary>
        public static string MenuButtonInvisible {
            get {
                return ResourceManager.GetString("MenuButtonInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string MenuButtonVisible {
            get {
                return ResourceManager.GetString("MenuButtonVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my people.
        /// </summary>
        public static string MenuMyPeople {
            get {
                return ResourceManager.GetString("MenuMyPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-Secure products.
        /// </summary>
        public static string MenuProducts {
            get {
                return ResourceManager.GetString("MenuProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tell a friend.
        /// </summary>
        public static string MenuTellAFriend {
            get {
                return ResourceManager.GetString("MenuTellAFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} minutes ago).
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now INVISIBLE.
        /// </summary>
        public static string NotificationYouAreInvisible {
            get {
                return ResourceManager.GetString("NotificationYouAreInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now VISIBLE.
        /// </summary>
        public static string NotificationYouAreVisible {
            get {
                return ResourceManager.GetString("NotificationYouAreVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string PivotMap {
            get {
                return ResourceManager.GetString("PivotMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string PivotMyPeople {
            get {
                return ResourceManager.GetString("PivotMyPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string PivotPlaces {
            get {
                return ResourceManager.GetString("PivotPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a place.
        /// </summary>
        public static string PlaceEditorAdd {
            get {
                return ResourceManager.GetString("PlaceEditorAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit place name.
        /// </summary>
        public static string PlaceEditorEdit {
            get {
                return ResourceManager.GetString("PlaceEditorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name for the place..
        /// </summary>
        public static string PlaceEditorNameHelp {
            get {
                return ResourceManager.GetString("PlaceEditorNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-press on the map to create your first place or tap the &quot;+&quot; sign in the menu to add the place in your current location..
        /// </summary>
        public static string PlacesHelp {
            get {
                return ResourceManager.GetString("PlacesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add places.
        /// </summary>
        public static string PlacesHelpTitle {
            get {
                return ResourceManager.GetString("PlacesHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot create more places. Maximum limit reached..
        /// </summary>
        public static string PlacesLimitReached {
            get {
                return ResourceManager.GetString("PlacesLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPageTitle {
            get {
                return ResourceManager.GetString("PrivacyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.f-secure.com/en/web/home_global/privacy/privacy-summary.
        /// </summary>
        public static string PrivacyReadMoreLink {
            get {
                return ResourceManager.GetString("PrivacyReadMoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more on our web site.
        /// </summary>
        public static string PrivacyReadMoreTitle {
            get {
                return ResourceManager.GetString("PrivacyReadMoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your privacy is of the utmost importance to us. Before you get started, you need to agree to the following terms:
        ///    
        ///1. I have read the terms of service and accept them.
        ///2. I consent to the collection and processing of personal data.
        ///3. I consent that the service can process and display my location.
        ///4. If I am under 15, I have my parents’ permission to use Lokki according to these terms.
        ///5. If I am under 13 and living in the United States, I may not use Lokki.
        ///    .
        /// </summary>
        public static string PrivacyTextMain {
            get {
                return ResourceManager.GetString("PrivacyTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select people you let see your location.
        ///Lokki will invite them via the selected email..
        /// </summary>
        public static string SearchHelp {
            get {
                return ResourceManager.GetString("SearchHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send log.
        /// </summary>
        public static string SendLog {
            get {
                return ResourceManager.GetString("SendLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible.
        /// </summary>
        public static string SettingInvisible {
            get {
                return ResourceManager.GetString("SettingInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Lokki ID is {0}.
        /// </summary>
        public static string SettingsLokkiId {
            get {
                return ResourceManager.GetString("SettingsLokkiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your frends need to use this email to let you see them in Lokki..
        /// </summary>
        public static string SettingsLokkiIdDescription {
            get {
                return ResourceManager.GetString("SettingsLokkiIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP MODE.
        /// </summary>
        public static string SettingsMapMode {
            get {
                return ResourceManager.GetString("SettingsMapMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY VISIBILITY.
        /// </summary>
        public static string SettingsMyVisibility {
            get {
                return ResourceManager.GetString("SettingsMyVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string SettingVisible {
            get {
                return ResourceManager.GetString("SettingVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on map.
        /// </summary>
        public static string ShowOnMap {
            get {
                return ResourceManager.GetString("ShowOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string SignupButton {
            get {
                return ResourceManager.GetString("SignupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error happened. Please check if entered email is valid and try again later.
        /// </summary>
        public static string SignupError {
            get {
                return ResourceManager.GetString("SignupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security reasons we need to authorize your account before you sign up again. Please follow the instructions we&apos;ve emailed to {0}..
        /// </summary>
        public static string SignupError401 {
            get {
                return ResourceManager.GetString("SignupError401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your email address - other Lokki users will be able to find you by using the same email address..
        /// </summary>
        public static string SignupExplanation {
            get {
                return ResourceManager.GetString("SignupExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.fsecure.com/lokki.
        /// </summary>
        public static string TellAFriendLink {
            get {
                return ResourceManager.GetString("TellAFriendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I&apos;m using F-Secure Lokki, the private location sharing app that&apos;s easy, secure, and free. Go to f-secure.com/lokki to install it..
        /// </summary>
        public static string TellAFriendMessage {
            get {
                return ResourceManager.GetString("TellAFriendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you don&apos;t 
        ///have any friends in Lokki yet.
        ///Add some?.
        /// </summary>
        public static string TutorialAddFriend {
            get {
                return ResourceManager.GetString("TutorialAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can now see you in Lokki. You will see your friends in Lokki when they grant you access. Add more friends via the &quot;+&quot; button..
        /// </summary>
        public static string TutorialCanSeeYou {
            get {
                return ResourceManager.GetString("TutorialCanSeeYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to F-Secure Lokki.
        /// </summary>
        public static string TutorialWelcome {
            get {
                return ResourceManager.GetString("TutorialWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where you are.
        /// </summary>
        public static string TutorialYouAreHere {
            get {
                return ResourceManager.GetString("TutorialYouAreHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.f-secure.com.
        /// </summary>
        public static string WebFSecureLink {
            get {
                return ResourceManager.GetString("WebFSecureLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.f-secure.com.
        /// </summary>
        public static string WebFSecureTitle {
            get {
                return ResourceManager.GetString("WebFSecureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.f-secure.com/en/web/home_global/privacy/privacy-summary.
        /// </summary>
        public static string WebPrivacyPolicyLink {
            get {
                return ResourceManager.GetString("WebPrivacyPolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string WebPrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("WebPrivacyPolicyTitle", resourceCulture);
            }
        }
    }
}
